import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: [
    {
      path: "../public/fonts/geist-sans/Geist-Variable.woff2",
      weight: "100 900",
      style: "normal",
      format: "woff2"
    }
  ],
  variable: "--font-geist-sans",
  display: "swap"
});

const geistMono = localFont({
  src: [
    {
      path: "../public/fonts/geist-mono/GeistMono-Variable.woff2",
      weight: "100 900",
      style: "normal",
      format: "woff2"
    }
  ],
  variable: "--font-geist-mono",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
